# Pré-processamento

In [58]:
import pandas as pd

CAMINHO = "C:\\Users\\Nitro\\PyCharmMiscProject\\Projetos_DeepLearning\\Classifica_textos_por_artista\\database\\artistas_textos.csv"

df = pd.read_csv(CAMINHO)
df = df.iloc[:, [1, 2]]
lista_autores_tirar = ["Bernardo Guimaraes","Adolfo Caminha", "Manuel Antonio de Almeida"]

df["autor"] = df["autor"].apply(lambda x: x.split("-")[0])
f = [str(x) + "-" + str(y) for x, y in enumerate(df["autor"])]
f = list(filter(lambda x: x.split("-")[-1] not in lista_autores_tirar, f))
indices = list(map(lambda x: int(x.split("-")[0]), f))
df = df.iloc[indices, :]
print(indices)
df

[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79]

               autor                                             textos
4    Aluisio Azevedo  A CONDESSA VÉSPER\nAluízio Azevedo\nAS MEMÓRIA...
5    Aluisio Azevedo  A Mortalha de Alzira, de Aluísio Azevedo\n\nFo...
6    Aluisio Azevedo                                                ...
7    Aluisio Azevedo  DEMÔNIOS\n\n\nAluísio Azevedo\n\n\n\nO meu qua...
8    Aluisio Azevedo                                                ...
..               ...                                                ...
75  Machado de Assis  Papéis Avulsos\nTexto-fonte:\nObra Completa, d...
76  Machado de Assis  Quincas Borba\nTexto-fonte:\nObra Completa, Ma...
77  Machado de Assis  Relíquias de Casa Velha\nTexto-fonte: Obra Com...
78  Machado de Assis  Ressurreição\nTexto-fonte:\nObra Completa, Mac...
79  Machado de Assis  Várias Histórias\nTexto-fonte:\nObra Completa,...

[70 rows x 2 columns]

In [40]:
print(df["autor"].value_counts())

autor
Jose de Alencar             23
Machado de Assis            17
Aluisio Azevedo             15
Joaquim Manuel de Macedo    15
Name: count, dtype: int64

In [41]:
# Remove duplicadas
autores = list(set(df["autor"]))
autores

['Joaquim Manuel de Macedo',
 'Jose de Alencar',
 'Machado de Assis',
 'Aluisio Azevedo']

In [43]:
num_caracteres_por_fragmentos = 500
dic_autores_caracteres = {}
for autor in autores:
    df_autor = df[df["autor"] == autor]
    livros = "\n".join(list(df_autor["textos"]))
    livros_fragmentados = [livros[c: c + 500] if len(livros) - c >= 500 else livros[c: len(livros) - c - 1] for c in range(0, len(livros), num_caracteres_por_fragmentos)]
    dic_autores_caracteres[autor] = livros_fragmentados

print(dic_autores_caracteres.keys())

dict_keys(['Joaquim Manuel de Macedo', 'Jose de Alencar', 'Machado de Assis', 'Aluisio Azevedo'])

In [61]:
# Criar dataframe com dados balanceados
dic_balanceados = {}
dic_balanceados["autor"] = [u + "-" + str(x) for u in dic_autores_caracteres.keys() for x in range(len(dic_autores_caracteres[u]))]
print(len(dic_balanceados["autor"]))
dic_balanceados["texto"] = [dic_autores_caracteres[u.split("-")[0]][int(u.split("-")[-1])] for u in dic_balanceados["autor"]]
print(len(dic_balanceados["texto"]))
print(dic_balanceados["autor"][76])
print(dic_balanceados['texto'][76])

40677
40677
Joaquim Manuel de Macedo-76
 se
olhar para elas meia hora sem pestanejar. Toda a dificuldade, porém, está em pintar
aquela mocinha que acaba de sentar-se pela sexta vez, depois que Augusto entrou
na sala: é a irmã de Filipe. Que beija-flor! Há cinco minutos que Augusto entrou e em
tão curto espaço já ela sentou-se em diferentes cadeiras, desfolhou um lindo pendão
de rosas, derramou no chapéu de Leopoldo mais de duas onças de água-de-colônia
de um vidro que estava sobre um dos aparadores, fez chorar uma criança, deu um
beli

In [55]:
df = pd.DataFrame.from_dict(dic_balanceados)

In [56]:
df.to_csv("C:\\Users\\Nitro\\PyCharmMiscProject\\Projetos_DeepLearning\\Classifica_textos_por_artista\\database\\artistas_textos_balanceados.csv")

In [59]:
print()

In [62]:
df = pd.read_csv("C:\\Users\\Nitro\\PyCharmMiscProject\\Projetos_DeepLearning\\Classifica_textos_por_artista\\database\\artistas_textos_balanceados.csv")

In [70]:
df[df["autor"].apply(lambda x: x.split("-")[0]) == "Machado de Assis"]

,Unnamed: 0,autor,texto
21601,21601,Machado de Assis-0,A Mão e a L...
21602,21602,Machado de Assis-1,...
21603,21603,Machado de Assis-2,"to que lha deu outrora,\ne, ao cabo, tudo pode..."
21604,21604,Machado de Assis-3,cia de 1874 \n ...
21605,21605,Machado de Assis-4,"principal, senão\nexclusivo, servindo-me a açã..."
...,...,...,...
31318,31318,Machado de Assis-9717,ntaxe. Aqui passou a mão panteísta de\nSpinoza...
31319,31319,Machado de Assis-9718,"es\ncortando, com a rapidez do amor e do desej..."
31320,31320,Machado de Assis-9719,"as de sacristia, caricaturas, facécias, dispar..."
31321,31321,Machado de Assis-9720,"uram-se e acham-se. Enfim, Sílvio achou Sílvia..."
31322,31322,Machado de Assis-9721,NaN